export const players = [
  { name: "John Smith", age: 25, position: "Forward", score: 85 },
  { name: "Emily Johnson", age: 28, position: "Midfielder", score: 78 },
  { name: "Michael Davis", age: 22, position: "Defender", score: 90 },
  { name: "Jessica White", age: 24, position: "Forward", score: 88 },
  { name: "Ryan Taylor", age: 27, position: "Midfielder", score: 82 },
  { name: "Sophia Brown", age: 23, position: "Defender", score: 87 },
  { name: "Daniel Wilson", age: 29, position: "Goalkeeper", score: 95 },
  { name: "Olivia Robinson", age: 26, position: "Midfielder", score: 79 },
  { name: "Ethan Miller", age: 24, position: "Defender", score: 91 },
  { name: "Ava Martinez", age: 28, position: "Forward", score: 84 },
  { name: "Matthew Garcia", age: 25, position: "Goalkeeper", score: 93 },
  { name: "Chloe Smith", age: 27, position: "Defender", score: 88 },
  { name: "Andrew Johnson", age: 23, position: "Midfielder", score: 81 },
  { name: "Emma Davis", age: 26, position: "Forward", score: 89 },
  { name: "William Brown", age: 29, position: "Defender", score: 92 },
  { name: "Sophie Taylor", age: 22, position: "Midfielder", score: 77 },
  { name: "David Wilson", age: 28, position: "Goalkeeper", score: 94 },
  { name: "Isabella White", age: 24, position: "Forward", score: 86 },
  { name: "Christopher Martinez", age: 26, position: "Midfielder", score: 80 },
  { name: "Grace Robinson", age: 30, position: "Defender", score: 85 },
];
